language: c

sudo: false

matrix:
  fast_finish: true
  include:
    # macOS build
    - env: INSTALL_TYPE=develop FITS="astropy" TEST=submodule MATPLOTLIBVER=2.0 TRAVIS_PYTHON_VERSION="3.6" XSPECVER="12.9.1u"
      os: osx
    # Barebone build to check tests pass when most of the tests must be skipped.
    # We need to use TEST=none to remove the test-data submodule.
#    - env: INSTALL_TYPE=develop TEST=none NUMPYVER=1.11 TRAVIS_PYTHON_VERSION="2.7"
#    # Full build (including ds9 and xspec), Python 2.7, setup.py develop, astropy, matplotlib 1.5
#    - env: XSPECVER="12.9.0i" NUMPYVER="1.11" FITS="astropy" INSTALL_TYPE=develop TEST=submodule MATPLOTLIBVER=1.5 TRAVIS_PYTHON_VERSION="2.7"
#      sudo: required
#      dist: trusty
#    # As above, Python 3.5
#    - env: XSPECVER="12.9.0i" NUMPYVER="1.11" FITS="astropy" INSTALL_TYPE=develop TEST=submodule MATPLOTLIBVER=1.5 TRAVIS_PYTHON_VERSION="3.5"
#      sudo: required
#      dist: trusty
#    # As above, Python 3.6, setup.py install
#    - env: XSPECVER="12.9.0i" NUMPYVER="1.11" FITS="astropy" INSTALL_TYPE=install TEST=submodule MATPLOTLIBVER=1.5 TRAVIS_PYTHON_VERSION="3.6"
#      sudo: required
#      dist: trusty
#    # As above, xspec 12.9.1n
#    - env: XSPECVER="12.9.1" NUMPYVER="1.14" FITS="astropy" INSTALL_TYPE=install TEST=submodule MATPLOTLIBVER=2.0 TRAVIS_PYTHON_VERSION="3.6"
#      sudo: required
#      dist: trusty
#    # Install sherpatest package rather than relying on relative location of the submodule
#    # Also, install matplotlib 2.0 and do not install astropy (checks tests are properly skipped)
#    - env: INSTALL_TYPE=install TEST=package MATPLOTLIBVER=2.0 TRAVIS_PYTHON_VERSION="2.7"
#    # Install astropy without matplotlib (checks tests are properly skipped)
#    - env: INSTALL_TYPE=develop TEST=submodule FITS="astropy" TRAVIS_PYTHON_VERSION="3.5"
#    # A relatively basic installation - NumPy and AstroPy - with no test data; this is similar to the preceeding
#    # test, so perhaps could be combined?
#    - env: INSTALL_TYPE=develop TEST=none FITS="astropy" TRAVIS_PYTHON_VERSION="3.5"

before_install:
  - source travis/setup_conda.sh

  # XSPEC and DS9
  - if [ -n "${XSPECVER}" ];
      then source travis/setup_xspec_ds9.sh;
    fi

install:
    - python setup.py $INSTALL_TYPE &> install.log

script:
  - source travis/test.sh

notifications:
  email:
    - olaurino@cfa.harvard.edu

