language: python

python:
  - "2.7"

sudo: false

cache:
  directories:
    - $HOME/xspec

addons:
  apt:
    packages: &default_apt
      - build-essential
      - gfortran
      - flex
      - bison

env:
  - FITS="astropy" INSTALL_TYPE=develop TEST=submodule
#  - FITS="pyfits" INSTALL_TYPE=develop TEST=submodule
#  - INSTALL_TYPE=install TEST=package
#  - FITS="astropy" INSTALL_TYPE=install TEST=package
#  - FITS="astropy" INSTALL_TYPE=install TEST=smoke
#  - INSTALL_TYPE=install TEST=smoke NOSETUPTOOLS="true"

matrix:
  include:
    - env: XSPEC="true" FITS="astropy" INSTALL_TYPE=develop TEST=submodule
      python: "2.7"
      sudo: required
      addons:
        apt:
          packages:
            - *default_apt
            - [libccfitsio0 libcfitsio3 libwcs4 libccfits-dev wcslib-dev libx11-dev tcl]

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy matplotlib
  - conda config --add channels https://conda.binstar.org/sherpa
  - pip install -r test_requirements.txt
  - if [ ${TEST} == package ];
     then pip install ./sherpa-test-data;
     git submodule deinit -f .;
    fi
  - if [ ${TEST} == smoke ];
     then git submodule deinit -f .;
    fi
  - if [ -n "${NOSETUPTOOLS}" ]; then conda remove --yes setuptools; fi
  - if [ -n "${XSPEC}" ];
    then
        sudo apt-get install -qq libccfits0 libcfitsio3 libwcs4 libccfits-dev wcslib-dev libx11-dev tcl;
        OLD_DIR=`pwd`;
        mkdir -p $HOME/xspec
        cd $HOME/xspec;
        XSPEC_HEASOFT_VERSION="6.16";
        XSPEC_PATCH="Xspatch_120802q.tar.gz";
        XSPEC_PATCH_INSTALLER="patch_install_4.6.tcl";
        wget -N http://heasarc.gsfc.nasa.gov/FTP/software/lheasoft/lheasoft${XSPEC_HEASOFT_VERSION}/xspec-modelsonly.tar.gz;
        tar xf xspec-modelsonly.tar.gz;
        wget -N http://heasarc.gsfc.nasa.gov/docs/xanadu/xspec/issues/${XSPEC_PATCH} -P xspec-modelsonly/Xspec/src;
        wget -N http://heasarc.gsfc.nasa.gov/docs/xanadu/xspec/issues/${XSPEC_PATCH_INSTALLER} -P xspec-modelsonly/Xspec/src;
        cd xspec-modelsonly/Xspec/xrc;
        tclsh ${XSPEC_PATCH_INSTALLER} -m -n;
        rm -rf XSFits;
        cd ../../BUILD_DIR;
        ./configure && make && make install;
        cd ../;
        if [ ! -e install ]; then ln -s x86_64* install; fi;
        export HEADAS=`pwd`/spectral;
        export XSPEC_LIBS=`pwd`/install/lib;
        export LD_LIBRARY_PATH=$XSPEC_LIBS;
        cd $OLD_DIR;
        sed -i.orig "s|#with-xspec=True|with-xspec=True|" setup.cfg;
        sed -i.orig "s|#xspec_lib_dirs = None|xspec_lib_dirs = $XSPEC_LIBS|" setup.cfg;
    fi

install:
  - python setup.py $INSTALL_TYPE

script:
  - if [ -n "${FITS}" ]; then conda install --yes ${FITS}; fi
  - if [ ${TEST} == submodule ]; then python setup.py test; fi
  - if [ ${TEST} == smoke ];
        then cd /home;
        python -c "import sherpa; sherpa.test()";
    fi
  - if [ ${TEST} == package ];
        then cd /home;
        sherpa_test;
    fi

notifications:
  email:
    - olaurino@cfa.harvard.edu

